tailwind.config = {
        darkMode: "class",
        theme: {
          extend: {
            colors: {
              "on-background": "#131b2e",
              "on-primary-fixed-variant": "#005137",
              "on-primary-container": "#f5fff7",
              "surface-tint": "#006c4a",
              "on-primary-fixed": "#002114",
              "outline": "#6d7a72",
              "error-container": "#ffdad6",
              "surface-variant": "#dae2fd",
              "on-secondary-fixed": "#131b2e",
              "secondary": "#565e74",
              "primary-fixed-dim": "#68dba9",
              "on-tertiary-fixed-variant": "#004395",
              "error": "#ba1a1a",
              "surface-container-low": "#f2f3ff",
              "on-error-container": "#93000a",
              "primary": "#006948",
              "on-error": "#ffffff",
              "surface-container-highest": "#dae2fd",
              "tertiary-fixed": "#d8e2ff",
              "on-secondary-container": "#5c647a",
              "on-surface": "#131b2e",
              "tertiary-fixed-dim": "#adc6ff",
              "surface-dim": "#d2d9f4",
              "on-secondary": "#ffffff",
              "background": "#faf8ff",
              "surface-bright": "#faf8ff",
              "primary-container": "#00855d",
              "inverse-on-surface": "#eef0ff",
              "surface": "#faf8ff",
              "inverse-primary": "#68dba9",
              "secondary-container": "#dae2fd",
              "tertiary-container": "#2170e4",
              "on-surface-variant": "#3d4a42",
              "on-tertiary": "#ffffff",
              "tertiary": "#0058be",
              "on-tertiary-container": "#fefcff",
              "surface-container": "#eaedff",
              "on-secondary-fixed-variant": "#3f465c",
              "on-tertiary-fixed": "#001a42",
              "primary-fixed": "#85f8c4",
              "inverse-surface": "#283044",
              "surface-container-high": "#e2e7ff",
              "outline-variant": "#bccac0",
              "surface-container-lowest": "#ffffff",
              "secondary-fixed": "#dae2fd",
              "secondary-fixed-dim": "#bec6e0",
              "on-primary": "#ffffff"
            },
            fontFamily: {
              "headline": ["Inter"],
              "body": ["Inter"],
              "label": ["Inter"]
            },
            borderRadius: {"DEFAULT": "0.25rem", "lg": "0.5rem", "xl": "0.75rem", "full": "9999px"},
          },
        },
      }